// app/components/QuantitySelector.tsx
import { useState } from "react";
import { HiMiniMinus, HiMiniPlus } from "react-icons/hi2";

export default function QuantitySelector() {
  const [quantity, setQuantity] = useState(1);

  return (
    <div className="flex justify-between items-center gap-4">
      <button
        className={`${
          quantity === 1 ? "opacity-25 pointer-events-none" : ""
        } w-12 lg:w-8 h-12 lg:h-8 bg-white flex justify-center items-center border-[1px] border-slate-200 rounded-md  hover:border-slate-500 transition-colors duration-300`}
        onClick={() => setQuantity(quantity - 1)}>
        <HiMiniMinus size={16} />
      </button>
      <p className="text-slate-700 font-semibold">Qty: {quantity}</p>
      <button
        className={`${
          quantity === 3 ? "opacity-25 pointer-events-none" : ""
        } w-12 lg:w-8 h-12 lg:h-8 bg-white flex justify-center items-center border-[1px] border-slate-200 rounded-md  hover:border-slate-500 transition-colors duration-300`}
        onClick={() => setQuantity(quantity + 1)}>
        <HiMiniPlus size={16} />
      </button>
    </div>
  );
}

// src/app/components/quantity-selector/quantity-selector.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-quantity-selector",
  templateUrl: "./quantity-selector.component.html",
})
export class QuantitySelectorComponent {
  @Input() quantity: number = 1;

  increment() {
    if (this.quantity < 3) {
      this.quantity++;
    }
  }

  decrement() {
    if (this.quantity > 1) {
      this.quantity--;
    }
  }
}

<div
  class="flex h-full w-full items-center justify-between gap-1 overflow-hidden rounded-md border border-slate-300 bg-white">
  <button
    class="cursor-pointer bg-white px-3 py-2 transition-colors duration-300 hover:bg-slate-50 active:bg-slate-100"
    (click)="decrement()">
    -
  </button>
  <div class="flex w-4 items-center justify-center">
    <span class="text-sm font-medium text-slate-700">{{ quantity }}</span>
  </div>
  <button
    class="cursor-pointer bg-white px-3 py-2 transition-colors duration-300 hover:bg-slate-50 active:bg-slate-100"
    (click)="increment()">
    +
  </button>
</div>
