// src/app/components/accordion-item/accordion-item.component.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { CustomIconComponent } from "@src/app/components/icon/custom-icon.component";

@Component({
  selector: "app-accordion-item",
  templateUrl: "./accordion-item.component.html",
  imports: [CommonModule, CustomIconComponent],
  standalone: true,
})
export class AccordionItemComponent {
  @Input() title!: string;
  @Input() isOpen = false;
}

<div class="flex w-full flex-col">
  <!-- Title -->
  <button
    class="flex w-full cursor-pointer items-center justify-between border-b border-slate-200 px-1 py-2"
    (click)="toggle()">
    <p class="text-sm font-semibold text-slate-600">{{ title }}</p>
    <div
      [ngClass]="{ '-rotate-180': isOpen }"
      class="flex h-8 w-8 items-center justify-center text-slate-500 transition-transform duration-150 hover:text-slate-400 active:text-slate-600">
      <app-custom-icon name="chevronDown" size="20"></app-custom-icon>
    </div>
  </button>
  <!-- Content -->
  @if (isOpen) {
    <div
      class="flex w-full items-center bg-slate-50 p-4 text-sm text-slate-600">
      <ng-content></ng-content>
    </div>
  }
</div>

// app/components/AccordionItem.tsx
import { useState } from "react";
import { HiChevronDown } from "react-icons/hi2";

export default function AccordionItem({
  label,
  details,
}: {
  label: string;
  details: string;
}) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="w-full flex flex-col justify-start items-stretch">
      <button onClick={() => setIsOpen(!isOpen)}>
        <div className="w-full py-2 px-4 border-b-[1px] border-slate-200 flex justify-between items-center">
          <p className="text-slate-700 font-semibold">{label}</p>
          <HiChevronDown size={16} className="text-slate-700" />
        </div>
      </button>
      {isOpen && (
        <div className="w-full p-4 bg-slate-50">
          <p className="text-sm text-slate-500">{details}</p>
        </div>
      )}
    </div>
  );
}
