// src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideSearch } from '@ng-icons/lucide';
import { HeaderUserButtonComponent } from './header-user-button/header-user-button.component';
import { HeaderCartButtonComponent } from './header-cart-button/header-cart-button.component';
@Component({
  selector: 'app-header',
  standalone: true,
  imports: [NgIcon, HeaderUserButtonComponent, HeaderCartButtonComponent],
  providers: [provideIcons({ lucideSearch })],
  templateUrl: './header.component.html',
})
export class HeaderComponent {}

<header class="w-screen bg-white flex flex-col justify-center items-stretch">
  <div id="top-header " class="w-full flex justify-center items-center py-3">
    <div class="nav-container">
      <div class="grid grid-cols-5 items-center gap-6 w-full">
        <div class="col-span-1 flex justify-start items-center shrink-0">
          <img
            src="/images/bhmd-logo-small.webp"
            class="w-auto h-[30px] object-contain lg:hidden"
          />
          <img
            src="/images/bhmd-logo-full.webp"
            class="w-auto h-[30px] object-contain hidden lg:block"
          />
        </div>
        <div class="col-span-3 flex justify-center items-center">
          <div class="w-full relative">
            <div
              class="absolute top-1/2 left-3 -translate-y-1/2 flex justify-center items-center text-slate-400"
            >
              <ng-icon name="lucideSearch" size="20" class=""></ng-icon>
            </div>
            <input
              type="search"
              name="search"
              id="search"
              placeholder="Search..."
              class="pl-10 pr-4 py-2.5 w-full"
            />
          </div>
        </div>
        <div class="col-span-1 flex justify-end items-center gap-2">
          <app-header-user-button></app-header-user-button>
          <app-header-cart-button></app-header-cart-button>
        </div>
      </div>
    </div>
  </div>
  <div id="bottom-header" class="w-full flex justify-center items-center">
    <div class="nav-container">
      <ul class="flex justify-around items-center w-full">
        <li class="nav-link-item">Shop All</li>
        <li class="nav-link-item">Best Sellers</li>
        <li class="nav-link-item">Bundles</li>
        <li class="nav-link-item">Supplements</li>
        <li class="nav-link-item">Cleansers</li>
        <li class="nav-link-item">Toners</li>
        <li class="nav-link-item">Exfoliants</li>
        <li class="nav-link-item">Moisturizers</li>
        <li class="nav-link-item">Eye + Lip Care</li>
        <li class="nav-link-item">Body</li>
        <li class="nav-link-item">Serums + Oils</li>
      </ul>
    </div>
  </div>
</header>

// app/components/Header.tsx
import { useState } from "react";
import { Link } from "@remix-run/react";
import Overlay from "./Overlay";
import ShopMegaMenu from "./ShopMegaMenu";
import {
  HiMiniChevronDown,
  HiMiniBars3,
  HiOutlineMagnifyingGlass,
  HiOutlineUserCircle,
  HiOutlineShoppingBag,
} from "react-icons/hi2";

export default function Header() {
  const [showShopMegaMenu, setShowShopMegaMenu] = useState(false);

  return (
    <div className="w-full h-auto sticky top-0 z-50 ">
      <header className="w-full bg-white py-4 border-b-[1px] border-slate-100 shadow-md">
        <div className="container">
          <div className="flex justify-between items-center">
            <button className="md:hidden">
              <HiMiniBars3 size={24} className=" text-slate-700" />
            </button>

            <div className="hidden md:flex justify-start items-center gap-2">
              <Link to="/">
                <img
                  src="/img/bhmd-logo.webp"
                  alt="Beverly Hills MD Cosmeceuticals"
                  className="w-auto h-8 object-contain"
                />
              </Link>
              <div className="w-[1px] h-6 bg-slate-400 mx-4"></div>
              <nav className="flex gap-4">
                <button
                  onClick={() => setShowShopMegaMenu(!showShopMegaMenu)}
                  className={`flex items-center gap-1 text-sm font-medium  transition-colors duration-300 ${
                    showShopMegaMenu
                      ? "text-blue-500"
                      : "text-slate-700 hover:text-blue-500"
                  }`}>
                  Shop All
                  <HiMiniChevronDown
                    size={16}
                    className={`transition-transform duration-300 ${
                      showShopMegaMenu ? "-rotate-180" : ""
                    } `}
                  />
                </button>
                <button className="flex items-center gap-1 text-sm font-medium  transition-colors duration-300 text-slate-700 hover:text-blue-500">
                  Discover
                  <HiMiniChevronDown
                    size={16}
                    className={`transition-transform duration-300 ${
                      showShopMegaMenu ? "-rotate-180" : ""
                    } `}
                  />
                </button>
                <Link
                  to="/posts"
                  className="text-slate-700 text-sm font-medium hover:text-blue-500 transition-colors duration-300">
                  Earn Rewards
                </Link>
              </nav>
            </div>
            <Link to="/">
              <img
                src="/img/bhmd-logo-small.webp"
                className="md:hidden w-auto h-8 object-contain"
                alt="Beverly Hills MD Cosmeceuticals"
              />
            </Link>
            <div className="flex justify-end items-center gap-4">
              <button className="hidden md:block">
                <HiOutlineMagnifyingGlass
                  size={24}
                  className=" text-slate-700"
                />
              </button>
              <Link to="/login" className="hidden md:block">
                <HiOutlineUserCircle size={24} className=" text-slate-700" />
              </Link>
              <button className="relative">
                <HiOutlineShoppingBag size={24} className=" text-slate-700" />
              </button>
            </div>
          </div>
        </div>
      </header>
      {showShopMegaMenu && (
        <Overlay>
          <ShopMegaMenu />
        </Overlay>
      )}
    </div>
  );
}
