// src/app/shared/components/header/header.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { AuthHeaderComponent } from "@src/app/features/auth-header/auth-header.component";
import { CustomIconComponent } from "@shared/components/custom-icon/custom-icon.component";
import { MegaMenuComponent } from "@src/app/features/mega-menu/mega-menu.component";

@Component({
  selector: "app-header",
  standalone: true,
  imports: [
    CommonModule,
    AuthHeaderComponent,
    CustomIconComponent,
    MegaMenuComponent,
  ],
  templateUrl: "./header.component.html",
})
export class HeaderComponent {
  isMegaMenuOpen = false;

  toggleMegaMenu() {
    this.isMegaMenuOpen = !this.isMegaMenuOpen;
  }

  showMegaMenu() {
    this.isMegaMenuOpen = true;
  }

  closeMegaMenu() {
    this.isMegaMenuOpen = false;
  }
}

<header class="fixed left-0 right-0 top-0 z-10 w-full shadow-md">
  <auth-header></auth-header>
  <section class="border-b border-slate-300 bg-white py-4">
    <div class="container">
      <div class="flex w-full items-center justify-between">
        <!-- Hamburger Menu -->
        <button class="h-6 w-6 lg:hidden">
          <app-custom-icon name="hamburger" size="24"></app-custom-icon>
        </button>
        <!-- Nav Left -->
        <div class="hidden items-center gap-4 lg:flex">
          <!-- Main Logo -->
          <a href="/">
            <img src="/images/bhmd-logo.webp" alt="Logo" class="h-8 w-auto" />
          </a>
          <div class="h-4 w-[1px] bg-slate-300"></div>
          <!-- Main Menu -->
          <nav class="flex gap-4">
            <button
              id="shop"
              class="nav-dropdown-link"
              (click)="toggleMegaMenu()"
            >
              <span>Shop</span>
              <app-custom-icon name="chevronDown" size="20"></app-custom-icon>
            </button>
            <button id="Learn" class="nav-dropdown-link">
              <span>Learn</span>
              <app-custom-icon name="chevronDown" size="20"></app-custom-icon>
            </button>
            <a href="/luxe-loyalty" class="nav-link">Earn Rewards</a>
          </nav>
        </div>
        <!-- Nav Center -->
        <a href="/" class="lg:hidden">
          <img src="/images/bhmd-small-logo.webp" alt="Logo" class="h-7 w-7" />
        </a>
        <!-- Nav Right -->
        <nav class="flex items-center justify-end gap-4">
          <button class="h-6 w-6">
            <app-custom-icon name="search" size="24"></app-custom-icon>
          </button>
          <button class="h-6 w-6">
            <app-custom-icon name="shoppingBag" size="24"></app-custom-icon>
          </button>
        </nav>
      </div>
    </div>
  </section>
  <app-mega-menu *ngIf="isMegaMenuOpen"></app-mega-menu>
</header>

// app/components/Header.tsx
import { Link } from "@remix-run/react";
import {
  HiOutlineMagnifyingGlass,
  HiOutlineUserCircle,
  HiOutlineShoppingBag,
} from "react-icons/hi2";

export default function Header() {
  return (
    <header className="sticky top-0 z-50 w-full bg-white py-4 border-b-[1px] border-slate-100 shadow-md">
      <div className="container">
        <div className="flex justify-between items-center">
          <div className="flex justify-start items-center gap-2">
            <img
              src="/img/bhmd-logo.webp"
              alt="Beverly Hills MD Cosmeceuticals"
              className="w-auto h-8 object-contain"
            />
            <div className="w-[1px] h-6 bg-slate-400 mx-4"></div>
            <nav className="flex gap-4">
              <Link
                to="/"
                className="text-slate-700 text-sm font-medium hover:text-blue-500 transition-colors duration-300">
                Shop All
              </Link>
              <Link
                to="/"
                className="text-slate-700 text-sm font-medium hover:text-blue-500 transition-colors duration-300">
                Earn Rewards
              </Link>
            </nav>
          </div>

          <div className="flex justify-end items-center gap-4">
            <HiOutlineMagnifyingGlass size={24} className=" text-slate-700" />
            <Link to="/login">
              <HiOutlineUserCircle size={24} className=" text-slate-700" />
            </Link>
            <HiOutlineShoppingBag size={24} className=" text-slate-700" />
          </div>
        </div>
      </div>
    </header>
  );
}
