// src/app/components/products/product-card/product-card.component.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterLink } from "@angular/router";
import { Product } from "../../../models/product.type";
@Component({
  selector: "app-product-card",
  imports: [CommonModule, RouterLink],
  templateUrl: "./product-card.component.html",
  standalone: true,
})
export class ProductCardComponent {
  @Input({ required: true }) product!: Product;
}

<a
  class="group flex w-full cursor-pointer flex-col"
  routerLink="/product/{{ product.slug }}">
  <div
    class="relative z-10 w-full overflow-hidden rounded-md shadow-sm transition-all duration-300 group-hover:-translate-y-1 group-hover:shadow-xl">
    @if (product.is_bestseller) {
      <app-bestseller></app-bestseller>
    }
    <img
      *ngIf="product?.image_url"
      [src]="product.image_url"
      alt="Product Image"
      class="h-48 w-full object-cover" />
  </div>
  <div class="flex flex-col justify-between p-1">
    <div class="relative h-5 self-start pr-2">
      <span
        class="relative z-20 text-[10px] leading-none font-semibold text-blue-800 uppercase"
        >{{ product.category }}</span
      >
      <div class="absolute bottom-0 z-10 h-2 w-full bg-rose-50"></div>
    </div>
    <h3 class="line-clamp-1 font-serif text-ellipsis text-blue-900">
      {{ product.name }}
    </h3>
    <p class="mb-1 line-clamp-2 text-sm text-ellipsis text-slate-500">
      {{ product.description }}
    </p>
    <p class="text-sm text-blue-800">
      <span class="font-serif italic">from </span>
      <span class="font-semibold tracking-wide">${{ product.price }}</span>
    </p>
  </div>
</a>

// app/components/ProductCard.tsx
import { Link } from "@remix-run/react";
import Rating from "./Rating";
import { Product } from "~/types/types";

export default function ProductCard({ product }: { product: Product }) {
  return (
    <Link
      to={`/product/${product.slug}`}
      className="w-full cursor-pointer group">
      <div className="w-100 h-48 relative rounded-md overflow-hidden group-hover:shadow-xl group-hover:-translate-y-1 group-hover:scale-[1.01] transition-all duration-300">
        {product.is_bestseller && (
          <div className="absolute top-2 left-2 px-2 py-1 text-xs font-medium rounded-sm uppercase bg-white text-slate-700">
            Best-seller
          </div>
        )}
        {product.image_url ? (
          <img
            src={product.image_url}
            alt={product.name}
            className="w-full h-full object-cover shadow-sm"
          />
        ) : (
          <div className="w-full h-full bg-slate-100"></div>
        )}
      </div>
      <div className="flex flex-col justify-start items-start p-2">
        <div className="pl-[2px] pr-2 relative">
          <div className="w-full h-2 bg-rose-50 absolute left-0 bottom-0 z-10"></div>
          <span className="uppercase text-[10px] text-blue-700 font-bold tracking-wider relative z-20">
            {product.product_categories.name}
          </span>
        </div>
        <h3 className="font-serif text-blue-900 font-medium text-lg line-clamp-1 overflow-ellipsis">
          {product.name}
        </h3>
        <Rating rating={product.rating} />
        <p className="text-sm text-slate-600 line-clamp-2 overflow-ellipsis mt-1 mb-2">
          {product.description}
        </p>
        <p className="text-sm text-blue-900">
          <span className="italic font-serif font-light mr-1">from</span>
          <span className="font-semibold tracking-wide">${product.price}</span>
        </p>
      </div>
    </Link>
  );
}
