// app/components/OfferSelector.tsx
import { Form } from "@remix-run/react";
import OfferSelectorOption from "./OfferSelectorOption";
import { HiMiniCheck } from "react-icons/hi2";

export default function OfferSelector({ price }: { price: number }) {
  return (
    <Form
      method="post"
      className="w-full flex flex-col justify-start items-stretch gap-4">
      <OfferSelectorOption label="Subscribe & Save" id="1" price={price}>
        <ul>
          <li className="flex justify-start items-center gap-1 text-slate-600 text-sm">
            <HiMiniCheck size={16} className="text-rose-500" />
            Save 5% on your first order
          </li>
          <li className="flex justify-start items-center gap-1 text-slate-600 text-sm">
            <HiMiniCheck size={16} className="text-rose-500" />
            Start earning points toward future orders
          </li>
          <li className="flex justify-start items-center gap-1 text-slate-600 text-sm">
            <HiMiniCheck size={16} className="text-rose-500" />
            Easily manage your subscription and cancel at any time
          </li>
        </ul>
      </OfferSelectorOption>
      <OfferSelectorOption label="One-time Purchase" id="2" price={price} />
      <input
        type="submit"
        value="Add to Cart"
        className="w-full px-6 py-3 bg-blue-600 text-white font-medium rounded-md shadow-md hover:bg-blue-500 active:bg-blue-700 transition-colors duration-300 cursor-pointer"
      />
      <div className="w-full flex justify-center items-center gap-2">
        <img src="/img/visa.webp" alt="Visa" className="w-8 h-auto" />
        <img
          src="/img/mastercard.webp"
          alt="Mastercard"
          className="w-8 h-auto"
        />
        <img src="/img/discover.webp" alt="Discover" className="w-8 h-auto" />
        <img
          src="/img/amex.webp"
          alt="American Express"
          className="w-8 h-auto"
        />
        <img src="/img/apple-pay.webp" alt="Apple Pay" className="w-8 h-auto" />
        <img src="/img/paypal.webp" alt="PayPal" className="w-8 h-auto" />
        <img src="/img/klarna.webp" alt="Klarna" className="w-8 h-auto" />
      </div>
    </Form>
  );
}

// src/app/features/offer-selector/offer-selector.component.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Product } from "../../models/product.type";

@Component({
  selector: "app-offer-selector",
  templateUrl: "./offer-selector.component.html",
  imports: [CommonModule],
  standalone: true,
})
export class OfferSelectorComponent {
  @Input() product!: Product;
  selectedOffer: "otp" | "sub" = "otp";

  selectOffer(offer: "otp" | "sub") {
    this.selectedOffer = offer;
  }

  constructor() {}
}

<div class="flex w-full flex-col items-stretch gap-2">
  <!-- One-Time Purchase -->
  <button
    class="flex w-full cursor-pointer items-center justify-between rounded-md border border-slate-300 px-4 py-3 transition-all duration-300"
    [ngClass]="
      selectedOffer === 'otp'
        ? 'border-transparent opacity-100 ring-2 ring-blue-500'
        : 'border-slate-300 opacity-60 hover:opacity-80'
    "
    (click)="selectOffer('otp')">
    <div class="flex flex-col justify-start">
      <div class="flex items-center gap-2">
        <div
          class="flex h-4 w-4 items-center justify-center rounded-full border transition-colors duration-300"
          [ngClass]="
            selectedOffer === 'otp' ? 'border-blue-500' : 'border-slate-300'
          ">
          <div
            class="h-[10px] w-[10px] rounded-full bg-blue-500 transition-opacity duration-300"
            [ngClass]="
              selectedOffer === 'otp' ? 'opacity-100' : 'opacity-0'
            "></div>
        </div>
        <div class="flex flex-col">
          <h6 class="self-start text-sm font-medium text-slate-600">
            One-Time Purchase
          </h6>
          <p class="text-xs text-slate-500">Pay once and own the product.</p>
        </div>
      </div>
    </div>
  </button>

  <!-- Subscribe + Save -->
  <button
    class="flex w-full cursor-pointer items-center justify-between rounded-md border border-slate-300 px-4 py-3 transition-all duration-300"
    [ngClass]="
      selectedOffer === 'sub'
        ? 'border-transparent opacity-100 ring-2 ring-blue-500'
        : 'border-slate-300 opacity-60 hover:opacity-80'
    "
    (click)="selectOffer('sub')">
    <div class="flex flex-col justify-start">
      <div class="flex items-center gap-2">
        <div
          class="flex h-4 w-4 items-center justify-center rounded-full border transition-colors duration-300"
          [ngClass]="
            selectedOffer === 'sub' ? 'border-blue-500' : 'border-slate-300'
          ">
          <div
            class="h-[10px] w-[10px] rounded-full bg-blue-500 transition-opacity duration-300"
            [ngClass]="
              selectedOffer === 'sub' ? 'opacity-100' : 'opacity-0'
            "></div>
        </div>
        <div class="flex flex-col">
          <h6 class="self-start text-sm font-medium text-slate-600">
            Subscribe + Save
          </h6>
          <p class="text-xs text-slate-500">
            Subscribe and save 20% + free shipping.
          </p>
        </div>
      </div>
    </div>
  </button>
</div>
